name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ACR_WebApp
    steps:
      - uses: actions/checkout@v4
          
      - uses: azure/docker-login@v1
        with:
          registry: demoazurecontainerregistry0206.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t demoazurecontainerregistry0206.azurecr.io/myapp:${{ github.sha }}
          docker push demoazurecontainerregistry0206.azurecr.io/myapp:${{ github.sha }}
